export const MCP_REGISTRY: Record<string, string> = {
  "ai-budget-planner": "https://ai-budget-planner-yd7bwat7eq-uc.a.run.app",
  "ai-expense-manager": "https://ai-expense-manager-yd7bwat7eq-uc.a.run.app",
  "ai-financial-analyst": "https://ai-financial-analyst-yd7bwat7eq-uc.a.run.app",
  "ai-financial-reporting-specialist": "https://ai-financial-reporting-specialist-yd7bwat7eq-uc.a.run.app",
  "ai-invoice-processor": "https://ai-invoice-processor-yd7bwat7eq-uc.a.run.app",
  "ai-payroll-manager": "https://ai-payroll-manager-yd7bwat7eq-uc.a.run.app",
  "ai-tax-compliance-agent": "https://ai-tax-compliance-agent-yd7bwat7eq-uc.a.run.app",
  "ai-training-coordinator": "https://ai-training-coordinator-yd7bwat7eq-uc.a.run.app",
  "ai-ux-analyst": "https://ai-ux-analyst-yd7bwat7eq-uc.a.run.app",
  "amazon-drop-shipping-ai": "https://amazon-drop-shipping-ai-yd7bwat7eq-uc.a.run.app",
  "coder-agent": "https://coder-agent-yd7bwat7eq-uc.a.run.app",
  "content-generation-ai": "https://content-generation-ai-yd7bwat7eq-uc.a.run.app",
  "cto-agent": "https://cto-agent-yd7bwat7eq-uc.a.run.app",
  "data-scrubbing-ai": "https://data-scrubbing-ai-yd7bwat7eq-uc.a.run.app",
  "designer-ai-agent": "https://designer-ai-agent-yd7bwat7eq-uc.a.run.app",
  "email-campaign-optimizer-ai": "https://email-campaign-optimizer-ai-yd7bwat7eq-uc.a.run.app",
  "fundraising-chatbot-ai": "https://fundraising-chatbot-ai-yd7bwat7eq-uc.a.run.app",
  "hr-ai-agent": "https://hr-ai-agent-yd7bwat7eq-uc.a.run.app",
  "information-retrieval-ai": "https://information-retrieval-ai-yd7bwat7eq-uc.a.run.app",
  "multimodal-ai": "https://multimodal-ai-yd7bwat7eq-uc.a.run.app",
  "org-scrubber-mcp": "https://org-scrubber-mcp-yd7bwat7eq-uc.a.run.app",
  "personalized-donation-ai": "https://personalized-donation-ai-yd7bwat7eq-uc.a.run.app",
  "qa-ai-agent": "https://qa-ai-agent-yd7bwat7eq-uc.a.run.app",
  "reporting-dashboard-ai": "https://reporting-dashboard-ai-yd7bwat7eq-uc.a.run.app"
};
