// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd8o8XH4vd4MmOtE_RH7qnl22kxNcl8zk',
    appId: '1:779610430003:web:6a6e0de1a2f12630ee6146',
    messagingSenderId: '779610430003',
    projectId: 'marines-ai-agent',
    authDomain: 'marines-ai-agent.firebaseapp.com',
    databaseURL: 'https://marines-ai-agent-default-rtdb.firebaseio.com',
    storageBucket: 'marines-ai-agent.appspot.com',
    measurementId: 'G-9MBFJZQLGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbXbBHi7A9lzwI84zzmNirQz8DukdHymE',
    appId: '1:779610430003:android:3d2b143f3c83c800ee6146',
    messagingSenderId: '779610430003',
    projectId: 'marines-ai-agent',
    databaseURL: 'https://marines-ai-agent-default-rtdb.firebaseio.com',
    storageBucket: 'marines-ai-agent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcTukkFkLwrVmWKv9wuCCXZitDXvLV3rw',
    appId: '1:779610430003:ios:6cea54eb5f137757ee6146',
    messagingSenderId: '779610430003',
    projectId: 'marines-ai-agent',
    databaseURL: 'https://marines-ai-agent-default-rtdb.firebaseio.com',
    storageBucket: 'marines-ai-agent.appspot.com',
    androidClientId: '779610430003-8t6cr01ni8vcmlhi6tgadeuqoo279vad.apps.googleusercontent.com',
    iosClientId: '779610430003-f9iv4vp41mkr5f8nledqo3ol5rt3ogh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.arborAidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcTukkFkLwrVmWKv9wuCCXZitDXvLV3rw',
    appId: '1:779610430003:ios:6cea54eb5f137757ee6146',
    messagingSenderId: '779610430003',
    projectId: 'marines-ai-agent',
    databaseURL: 'https://marines-ai-agent-default-rtdb.firebaseio.com',
    storageBucket: 'marines-ai-agent.appspot.com',
    androidClientId: '779610430003-8t6cr01ni8vcmlhi6tgadeuqoo279vad.apps.googleusercontent.com',
    iosClientId: '779610430003-f9iv4vp41mkr5f8nledqo3ol5rt3ogh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.arborAidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd8o8XH4vd4MmOtE_RH7qnl22kxNcl8zk',
    appId: '1:779610430003:web:e6fd6ab6645a2e43ee6146',
    messagingSenderId: '779610430003',
    projectId: 'marines-ai-agent',
    authDomain: 'marines-ai-agent.firebaseapp.com',
    databaseURL: 'https://marines-ai-agent-default-rtdb.firebaseio.com',
    storageBucket: 'marines-ai-agent.appspot.com',
    measurementId: 'G-5N75XV3Q8E',
  );
}
